title:
  高知県高岡郡津野町
description:
  津野町内でテイクアウトできるお店
data_url:
  https://docs.google.com/spreadsheets/d/1Z8EprD-WTibCOP5GA1P-AOM0co5Km7i_GSuAKTpZ87I/export?format=csv&gid=0
repository:
  https://github.com/mimosafa/tsuno.iemeshi/
form_url:
  https://docs.google.com/forms/d/e/1FAIpQLSeaHT2tXCWXn7ySuzbegRrAho18VcvTABf55j6YCkuhz-elNw/viewform?usp=sf_link
